architecture: deepspeech2
bidirectional: True
use_bidirectional: True
hidden_dim: 512
dropout: 0.3
num_encoder_layers: 3
rnn_type: gru
max_len: 400
activation: clipped_relu # cnn activation function
teacher_forcing_ratio: 1.0
teacher_forcing_step: 0.0
min_teacher_forcing_ratio: 1.0
joint_ctc_attention: false