# data
dataset: 'kspon'
dataset_path: ''
transcripts_path: '/workspace/data/transcripts.txt'
output_unit: 'character'

# trainer
num_epochs: 20
batch_size: 128
save_result_every: 1000
checkpoint_every: 5000
print_every: 10
mode: 'train'
seed: 777
resume: false

# device
num_workers: 4
use_cuda: True

# optim
optimizer: 'adamp'
init_lr: 1e-05
final_lr: 1e-05
peak_lr: 1e-03
init_lr_scale: 0.01
final_lr_scale: 0.05
max_grad_norm: 400
warmup_steps: 35000
weight_decay: 1e-04
reduction: 'mean'